name: my workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

#    - name: Setup Node.js
 #     uses: actions/setup-node@v2
  #    with:
        # Specify the Node.js version you want to install (e.g., 14.x)
   #     node-version: '14.x'

    - name: build app
      run: |
        npm install
        npm run build



